name: Release & Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

      - name: Trigger dploy on server
        run: |
          curl -X POST https://bot.fpcorporativo.com:7080/deploy \
            -H "Authorization: Bearer Miflakota1*" \
            -H "Content-Type: application/json" \
            -d '{"project": "ws_bot_filemngr_laravel_vue"}'
